apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app
        image: 733787730018.dkr.ecr.us-east-1.amazonaws.com/thuy-udacity-repo:latest
        ports:
        - containerPort: 3000